version: '2'
services:

  # The Application
  app:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    working_dir: /var/www
    volumes:
      - ./app-data:/var/www
    environment:
      - DB_PORT=3306
      - DB_HOST=database
  # The Web Server
  web:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 80:80
  # The Database
  database:
    image: mysql:5.7
    volumes:
      - ./data-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dfgdfgdfgdfgdYX^bz@
      - MYSQL_DATABASE=alb
      - MYSQL_USER=alb123easyStreet
      - MYSQL_PASSWORD=PieisAWeSome124241
    ports:
      - "3306:3306"
volumes:
    dbdata: